:schedule:
  BatchUpdateTrackDataJob:
    # Every day at 12:00am CST
    cron: '0 5 * * *'

  BatchUpdateArtistsGenresJob:
    # Every day at 1:00am CST
    cron: '0 6 * * *'

  BatchUpdateArtistsFallbackGenresJob:
    # Every day at 2:00am CST
    cron: '0 7 * * *'
